nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin:
            - '*'
        allow_headers:
            - 'Content-Type'
            - 'Authorization'
            - 'X-Requested-With'
        allow_methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
        expose_headers: []
        max_age: 3600
        origin_regex: true
    paths:
        '^/api/':
            allow_origin:
                - 'https://example.com'
            allow_methods:
                - POST
                - GET

